baseURL = 'http://oliveratkinson.us'
languageCode = 'en-us'
title = 'Oliver Atkinson'
theme = 'lugo'

[taxonomies]
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true